{{- if .Values.podDisruptionBudget.enabled }}
{{- if and (ne .Values.podDisruptionBudget.minAvailable nil) (ne .Values.podDisruptionBudget.maxUnavailable nil) }}
{{- fail "podDisruptionBudget.minAvailable and maxUnavailable are mutually exclusive" }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "braiins-pool-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "braiins-pool-exporter.labels" . | nindent 4 }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "braiins-pool-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
