---
apiVersion: v2
name: braiins-pool-exporter
description: Prometheus exporter for Braiins Pool mining statistics
type: application
version: 0.1.0
appVersion: "0.0.1"
kubeVersion: ">=1.25.0-0"
home: https://github.com/nicosmuts/braiins-pool-exporter
icon: https://raw.githubusercontent.com/nicosmuts/braiins-pool-exporter/main/assets/banner-image.png
sources:
  - https://github.com/nicosmuts/braiins-pool-exporter
  - https://github.com/nicosmuts/helm-charts
maintainers:
  - name: Nico Smuts
    url: https://github.com/nicosmuts
keywords:
  - braiins
  - mining
  - prometheus
  - exporter
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/nicosmuts/braiins-pool-exporter
    - name: Chart source
      url: https://github.com/nicosmuts/helm-charts
